---

- hosts: localservers
  tasks:
    - name: Check debug modules
      copy:
       dest: /tmp/foo.txt
       content: |
         Good Morning!
         Awesome sunshine today.
       register: display_file_content
    - name: Debug display_file_content
      debug:
        var: display_file_content
        verbosity: 2

#https://linuxhint.com/ansible_debug_module/